version: "3.8"

services:
  grpc-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.grpc
    container_name: grpc-container
    volumes:
      - ./proto_files:/app/proto_files
      - ./generated:/app/generated
    working_dir: /app
    command: >
      /bin/bash -c "mkdir -p /app/generated &&
      protoc -I=/app/proto_files
      --cpp_out=/app/generated
      --grpc_out=/app/generated
      --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin
      /app/proto_files/task.proto"

  prestart-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prestart
    container_name: prestart-container
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    working_dir: /app
    command: >
      /bin/bash -c "echo 'Running prestart setup'"

  vcpkg-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.vcpkg
    container_name: vcpkg-container
    volumes:
      - ./vcpkg:/app/vcpkg
    working_dir: /app
    command: >
      /bin/bash -c "./vcpkg/bootstrap-vcpkg.sh && echo 'VCPKG setup complete'"
