apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - name: cql
      protocol: TCP
      port: 9042
      targetPort: 9042
    - name: intra-node
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: intra-node-tls
      protocol: TCP
      port: 7001
      targetPort: 7001
    - name: jmx
      protocol: TCP
      port: 7199
      targetPort: 7199
  type: ClusterIP
