apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-cql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # Должен совпадать с PV
