apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  namespace: ${KUBERNETES_NAMESPACE}
  labels:
    app: cassandra
spec:
  clusterIP: None # Headless сервис для прямого доступа к каждому узлу
  ports:
  - name: cql
    port: 9042
  - name: intra-node
    port: 7000
  - name: intra-node-tls
    port: 7001
  - name: jmx
    port: 7199
  selector:
    app: cassandra
