apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: ${KUBERNETES_NAMESPACE}
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: coordinator:latest
        ports:
        - containerPort: ${COORDINATOR_PORT}
        env:
        - name: COORDINATOR_PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: COORDINATOR_PORT
