apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
